services:
  proxy:
    build:
      context: ..
      dockerfile: .deploy-alternative/nginx/Dockerfile
    ports:
      - "${PROXY_PORT:-80}:80"
    volumes:
      - ../src:/project
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: .deploy-alternative/php/Dockerfile
      args:
        USER: ${USER:-user}
    #entrypoint: ["/bin/sh", "-c", "composer install && yes | php artisan migrate:fresh --seed && yes |php-fpm"]
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME:-retmix}
      - DB_USERNAME=${DB_USER:-retmix}
      - DB_PASSWORD=${DB_PASSWORD:-retmix}
    volumes:
      - ../src:/project
    depends_on:
      - db

  db:
    image: quay.io/sclorg/postgresql-15-c9s
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME:-retmix}
      POSTGRESQL_USER: ${DB_USER:-retmix}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD:-retmix}
    ports:
      - "5432:5432"
