services:
  proxy:
    build:
      context: ..
      dockerfile: .deploy/nginx/Dockerfile
    ports:
      - "${PROXY_PORT:-80}:80"
    volumes:
      - ../src:/project
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: .deploy/php/Dockerfile
      args:
        USER: ${USER:-user}
    #entrypoint: ["/bin/sh", "-c", "composer install && yes | php artisan migrate:fresh --seed && yes |php-fpm"]
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME:-postgres}
      - DB_USERNAME=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - ../src:/project
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"